name: baker_street_inquirer
description: A new Flutter project.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.5.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.0.3
  cupertino_icons: ^1.0.5
  device_preview: ^1.1.0
#  path_provider_fde:
#    git:
#      url: https://github.com/google/flutter-desktop-embedding/
#      path: plugins/flutter_plugins/path_provider_fde

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Cambria
      fonts:
        - asset: fonts/cambria-bold.ttf
          weight: 700
        - asset: fonts/cambria-regular.ttf
          weight: 400
        - asset: fonts/cambria-bold-italic.ttf
          style: italic
          weight: 700
        - asset: fonts/cambria-italic.ttf
          style: italic
          weight: 400
    - family: Hoefler-text
      fonts:
        - asset: fonts/hoefler-text-black.ttf
          weight: 900
        - asset: fonts/hoefler-text-regular.ttf
          weight: 400
        - asset: fonts/hoefler-text-black-italic.ttf
          style: italic
          weight: 900
        - asset: fonts/hoefler-text-italic.ttf
          style: italic
          weight: 400
    - family: Book-Antiqua
      fonts:
        - asset: fonts/book-antiqua-bold.ttf
          weight: 700
    - family: LibreBaskerville
      fonts:
        - asset: fonts/librebaskerville-bold.ttf
          weight: 700
        - asset: fonts/librebaskerville-regular.ttf
          weight: 400
        - asset: fonts/librebaskerville-italic.ttf
          style: italic
          weight: 400


